name: deploy-front-end
run-name: ${{ github.actor }} is pushing changes to front end for deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    # use bash shell regardless of runner
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: azure login
        uses: azure/login@v1.1.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: setup tf
        uses: hashicorp/setup-terraform@v3

      - run: cd terraform
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan -input=false
      - run: terraform apply
    