name: deploy-front-end
run-name: ${{ github.actor }} is pushing changes to front end for deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    # use bash shell regardless of runner
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: setup tf
        uses: hashicorp/setup-terraform@v3

      - name: tf init
        working-directory: ./terraform
        run: terraform init

      - name: tf fmt
        working-directory: ./terraform
        run: terraform fmt -check

      - name: tf plan
        working-directory: ./terraform
        run: terraform plan -out tfplan

      - name: tf apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan